<?php
// Debug Cloudinary configuration
require_once __DIR__ . '/api/Config/cloudinary.php';

header('Content-Type: application/json');

echo json_encode([
    'CLOUDINARY_CLOUD_NAME' => CLOUDINARY_CLOUD_NAME,
    'CLOUDINARY_API_KEY' => CLOUDINARY_API_KEY ? 'SET' : 'NOT SET',
    'CLOUDINARY_API_SECRET' => CLOUDINARY_API_SECRET ? 'SET' : 'NOT SET',
    'CLOUDINARY_UPLOAD_PRESET' => CLOUDINARY_UPLOAD_PRESET,
    'CLOUDINARY_BASE_URL' => CLOUDINARY_BASE_URL,
    'CLOUDINARY_FOLDERS' => CLOUDINARY_FOLDERS,
    'CLOUDINARY_ALLOWED_MIME_TYPES' => CLOUDINARY_ALLOWED_MIME_TYPES,
    'CLOUDINARY_MAX_FILE_SIZE' => CLOUDINARY_MAX_FILE_SIZE,
    'timestamp' => date('Y-m-d H:i:s')
], JSON_PRETTY_PRINT);
?>
